import type { Metadata } from "next";
import "./globals.css"; // <-- این خط حتما باید باشد
import { cn } from "@/lib/utils"; // <-- اضافه کردن کلاس cn (اگر وجود ندارد، یک فایل lib/utils.ts بسازید)
import PWARegister from "@/components/PWARegister";

export const metadata: Metadata = {
  title: "برج یار",
  description: "مدیریت سالن و خدمات برج",
  manifest: "/manifest.json", // ← لینک به فایل manifest.json در پوشه public

  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "برج یار",
  },
  icons: {
    apple: "/icons/icon-192x192.png",
  },
};

export const viewport = {
  themeColor: "#3b82f6",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={cn("min-h-screen bg-background text-foreground")}>
        {/* <HeaderMenu /> */}
        {/* <div className="pt-20">{children}</div> */}
        {children}
        <PWARegister />
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
