import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css"; // <-- این خط حتما باید باشد
import { cn } from "@/lib/utils"; // <-- اضافه کردن کلاس cn (اگر وجود ندارد، یک فایل lib/utils.ts بسازید)
// import HeaderMenu from "@/components/HeaderMenu";
//const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <title>برج یار</title>
      </head>
      <body className={cn("min-h-screen bg-background text-foreground")}>
        {/* <HeaderMenu /> */}
        {/* <div className="pt-20">{children}</div> */}
        {children}
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
